services:
  postgres:
    image: "postgres:15"
    restart: "always"
    volumes:
      - ./.psql/:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "user"
      POSTGRES_DB: "test"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@fkmail.com"
      PGADMIN_DEFAULT_PASSWORD: "senha"
    ports:
      - "1234:80"
  mkdocs:
    image: squidfunk/mkdocs-material
    ports:
      - "8005:8000"
    volumes:
      - ./:/docs
    stdin_open: true
    tty: true