site_name: D&D Clássico
site_url: https://sbd1.github.io/2024.2-D-D-classico/
repo_url: https://github.com/SBD1/2024.2-D-D-classico

nav:
  - Home: 'index.md'
  - Módulo 1:
    - Diagrama Entidade Relacionamento: 'DER.md'
    - Modelo Entidade Relacionamento: 'MER.md'
    - Dicionário: 'dicionario.md'
  - Apresentações:
    - Módulo 1: 'apresentacao1.md'

theme:
  name: material
  language: pt
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: red
      accent: black 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: red
      accent: blue
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
  plugins:
  - search